# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'dra1n' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dra1n
  pod "Macaw", "0.9.6"
  pod 'SwiftyMarkdown'
  pod 'SwiftyOnboard'
end

target 'dra1n-jailed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dra1n
  pod "Macaw", "0.9.6"
  pod 'SwiftyMarkdown'
  pod 'SwiftyOnboard'
end


